### ISSUE TITLE
[FEATURE] Replace actor start/stop events with actor_scaled event

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#1092]
**Is your feature request related to a problem? Please describe.**
There are currently 4 events related to scaling an actor:
- `actor_started`
- `actor_stopped`
- `actors_started`
- `actors_stopped`

**Describe the solution you'd like**
I propose we use a single event to capture all of these: `actor_scaled`

**Describe alternatives you've considered**
N/A

**Additional context**
I'm not sure how this impacts wadm, so would appreciate input from @brooksmtownsend @thomastaylor312

**Comment by MeenuyD** [comment]
Hello @connorsmith256 I would like to work on this issue can you please assign it to me I have a question should we have to replace all the `actors_started` and `actors_stopped` to `actors_scaled`

**Comment by brooksmtownsend** [comment]
w.r.t. wadm, it would be nice if we introduced the new `actor_scaled` event and deprecate the others so that we can work forwards with backwards compatibility for a release or two. 

Ideally:
1. Add `actor_scaled` to the list of events, emitted whenever an actor is started, stopped, or scaled. If there's a cloudevents way to mark an event deprecated (TBD) we should do that too.
2. Note in that wasmCloud release that the other events are deprecated.
3. Update wadm and wash to expect the `actor_scaled` event.
4. Remove old events

Question: How do we treat the idea of scaling an actor with no maximum concurrency? Does an `actor_scaled` event with a max of 0 mean infinite, or that it stopped?
Strawman answer: Scaling to 0 means that the actor is no longer running. Actually scaling with a maximum level of concurrency should be supported with a big number, e.g. if the scale is a u16 we should represent the max as `65536`.

**Comment by brooksmtownsend** [comment]
#1107 will remove `actor_started` and `actor_stopped` and `actor_start_failed` in favor of `actor_scaled`, but leaves the plural events for now so we can make the compatible changes in wadm, the lattice observer, wash, etc.

**Comment by brooksmtownsend** [comment]
Closed in #1107
