### ISSUE TITLE
[BUG] echo-tinygo template broken due to preview1-triggered wit generation

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#1241]
**Describe the bug**
Wash integration tests fail in CI

**To Reproduce**
1. https://github.com/wasmCloud/wasmCloud/actions/runs/7325077061 this seems to be the first occurrence

**Expected behavior**
Success

**Additional context**
It seems pretty clear, that these tests are nondeterministic, so I doubt this is the last time they will break. Is there a reason we cannot avoid relying on fetching from external sources in these tests?

**Comment by brooksmtownsend** [comment]
I believe @vados-cosmonic did a good bit of work to make these deterministic, the issue here of
```
missing `wit_world` in wasmcloud.toml ([actor] section) to run go bindgen generate
```

seems like something we can fix 🤔

**Comment by vados-cosmonic** [comment]
Yeah I don't think this issue actually reflects the failure that was found (and linked), slightly more information around that line that you found, Brooks:

```
 missing `wit_world` in wasmcloud.toml ([actor] section) to run go bindgen generate
thread 'integration_build_tinygo_actor_unsigned' panicked at crates/wash-cli/tests/wash_build.rs:304:5:
assertion failed: status.success()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So after doing some digging it looks like this is the confluence of a couple things:

- `wash` attempts to perform bindgen on preview1 *or* preview2 components
- the `echo-tinygo` example has a `wash_target` of `wasm32-wasi-preview1`
- the `echo-tinygo` component uses absolutely no component-relevant machinery

Building preview1 or preview2 does not technically mean that WIT is involved, so there's a mismatch there -- but we want to be WIT-first so I'm not sure if that check should be changed. 

The template builds just fine if we *remove* `wasm_target` (so it defaults to `CoreModule` (i.e. `wasm32-unknown-unknown`) which builds and is usable from the host just fine.

There are a few ways we can fix this, but I'm thinking of two things:

**At the `wash` level** we can update the check to at least make sure there *is* a `wit` directory at all (i.e. the project should be built using bindgen). We currently don't expect/let people change the directory where WIT is specified (it could technically be another dir) so that should at least indicate that 

**At the templates level** we should remove that setting ASAP until `wash` is released with the fix, so we don't break current users.

**Comment by brooksmtownsend** [comment]
Fairly sure we fixed this right @vados-cosmonic ?

**Comment by vados-cosmonic** [comment]
Yup this is fixed -- there's one more optional thing which is re-adding `wasm_target` (to build preview1 components versus modules), but that's not strictly necessary!
