### ISSUE TITLE
[BUG] extras:request_random fails without returning error, if actor isn't signed with wasmcloud:extras capability

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmCloud#137]
**Describe the bug**
If an actor not signed with wasmcloud:extras calls extras::default().request_random, an unhelpful log message is generated, and no error is returned from the api.

The log entry is "Error invoking actor: Guest call failure: [trap] unreachable executed (from wasmbus://MCU3HHBS2GKPCR6ZUEL7KULLO6K3KU5IPYUH3JK6YGVUSQCHF3S6NI5T/HandleRequest)"

(The code below was in an http handler. The result was that it returned status 500). 

**To Reproduce**
In an actor function (in this case it was an http handler)

    match extras::default().request_random(0, 10) {
        Ok(val)=> debug!("Random value: {}", val),
        Err(e) => debug!("Error: {}", e.to_string())
    }

**Expected behavior**
Expected: (1) the request_random function returns Err(e) with a helpful error, and (2) there's a wasmcloud log entry describing the problem.

A helpful message might say: "Actor attempted to invoke extras:<function> but the actor is not signed with the required wasmcloud:extras capability

**Environment (please complete the following information) **
- wasmcloud 0.16.0
- extras 0.1.1

**Comment by autodidaddict** [comment]
It looks like the issue here could be related to the fact that the code inside `wapc_host_callback` is ignoring the scenario when an `InvocationResponse` includes an error. If a security failure occurs, then we automatically convert those into `InvocationResponse::failure`s.

The offending line of code: 
```
match block_on(async { bus.send(inv).await.map(|ir| ir.msg) }) {
```
We're automatically mapping to the invocation response payload, _even if it's an error_
