### ISSUE TITLE
[BUG] wash build on windows appears to be broken

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wasmCloud#1481]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

wash build failing on windows

### Steps to reproduce

Following the quickstart on windows:
```bash
cargo install wash-cli
wash new actor --git wasmcloud/wasmcloud --subfolder examples/rust/actors/http-hello-world hello
rustup target add wasm32-wasi
cd hello
wash build
```

`wash build` fails with:
`Could not find compiled wasm file, please ensure \\?\C:\Users\marku\wcloudtraining\hello\target/wasm32-wasi/release/http_hello_world.wasm exists`

### Expected behavior

No errors and a signed component is built.

### Environment

- OS: [Windows]
- Shell [powershell]
- wasmcloud Version [0.81.0]

### Screenshots / Logs / Additional context

Potentially related https://github.com/wasmCloud/wash/issues/341

**Comment by MarkusEicher** [comment]
I encounter this behavior on my Windows 11 system. There is a post on the r/wasmcloud Reddit in which Brooks Townsend gave some hints how to fix the problem. It is under the following link.

https://www.reddit.com/r/wasmcloud/comments/15ywjp1/wash_build_error/?rdt=35012

I tried the following steps:

Adding a section [rust] to the wasmcloud.toml file as follows:

```
name = "http-hello-world"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = [
  "wasmcloud:httpserver",
]
wit_world = "hello"
wasm_target = "wasm32-wasi-preview2"

[rust]
target_path = "/wasm32-wasi/release/http_hello_world.wasm"
```
This lead to the following different error message:

> Could not find compiled wasm file, please ensure /wasm32-wasi/release/http_hello_world.wasm/wasm32-wasi/release/http_hello_world.wasm exists

It seems that this won't help, because whatever target_path you enter into the [rust] section, it will always take this entry and put it before the path /wasm32-wasi/release/http_hello_world.wasm.

Not sure if this helps anyone, I just wanted to mention that I tried this.

**Comment by MarkusEicher** [comment]
It seems that there is one notation in the [rust] section that fixes the error. You might want to check if this is the case also on your dev system.

With the following version of the wasmcloud.toml file it works on my system:

```
name = "http-hello-world"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = [
  "wasmcloud:httpserver",
]
wit_world = "hello"
wasm_target = "wasm32-wasi-preview2"

[rust]
target_path = "C:\\Users\\marku\\wasmcloudt\\hello\\target"
```

This leads to the following output:

```
 $ wash build
    Finished release [optimized] target(s) in 0.05s

Actor built and signed and can be found at "\\\\?\\C:\\Users\\marku\\wasmcloudt\\hello\\build\\http_hello_world_s.wasm"
```
I then can deploy the app with wash app deploy wadm.yaml

```
$ wash app deploy wadm.yaml

Successfully deployed model rust-http-hello-world v0.0.1
```

**Comment by MarkusEicher** [comment]
Just to let you know, but there seems to be another glitch when doing the manual fix on my Windows 11 system as described above. After the deployment seemed to be successful and I enter `wash app list` I noticed that the state of the app is `Undeployed`. After changing the manifest version to v0.0.2 and another deployment the situation remained the same. It did also not help to use the `wasmcloud.azurecr.io/hello:0.1.7` default image instead of a custom one.

```
PS C:\Users\marku\wasmcloudt\hello> wash app deploy wadm.yaml

Successfully deployed model rust-http-hello-world v0.0.2
PS C:\Users\marku\wasmcloudt\hello> wash app list



  Name                    Latest Version   Deployed Version   Deploy Status   Description

  rust-http-hello-world   v0.0.2           v0.0.2                Undeployed   HTTP hello world demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)
```
I'm not sure, if this is a problem of my local installation or if it may be relevant for this issue and how to fix it. I did not do any further troubleshooting yet. Please just let me know, if you need further information or troubleshooting steps from me.
