### ISSUE TITLE
[BUG] wasmcloud_provider_wit_bindgen::generate macro fails if two interfaces depend on the same third interface

### ISSUE THREAD

**Issue by wamli** [wasmCloud/wasmCloud#1567]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [X] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

This bug report is about the `wasmcloud_provider_wit_bindgen::generate` macro, e.g. as described [here](https://github.com/wasmCloud/wasmCloud/tree/main/crates/provider-wit-bindgen). 

### Problem description:

Given a provider which imports one interface and that exports another interface. The imported interface shall be served by a linked actor later on. The exported interface shall be what was done by Smithy before:

**[wamli-mlprovider.wit]**
```
package wamli:mlprovider;

world wamli-mlprovider {
   export wamli:ml/inference;
   import wamli:ml/model;
}
```

Both interfaces depend on the same types. This fact seems to be what the compiler does not like:

**[inference.wit]**
```
interface inference {
   use types.{
      tensor,
      status,
   };
// [..]
}
```

**[model.wit]**
```
interface model {
   use types.{
      execution-target,
      value-type,
      dimensions,
      ml-error,
   };
// [..]
}
```

**[types.wit]**
```
interface types {
   enum execution-target {
      cpu,
      gpu,
      tpu,
   }
// [..]
}
```

The intent is to drive all that with the known macro:
**[lib.rs]**
```
wasmcloud_provider_wit_bindgen::generate!({
    impl_struct: AiModelProvider,
    contract: "wamli:ml",
    wit_bindgen_cfg: "wamli-mlprovider"
});
```
The error is as described above: `could not find 'wamli' in the crate root .`
All interfaces are in a common package.

### Steps to reproduce

Just try to compile the above

### Expected behavior

It should just compile

### Environment

- OS: Linux, Ubuntu 22
- Shell: bash
- wasmcloud Version: 0.81

**Comment by vados-cosmonic** [comment]
Hey @wamli thanks for the report and the detailed test case! 

I'll reproduce this and look into it -- I think this is most likely caused by those imports getting duplicated. We do some de-duplication when dealing with the bindgen'd import vs export output, but I'll see if this is something that can be easily fixed.

**Comment by vados-cosmonic** [comment]
Hey @wamli I know you found a workaround thanks to @thomastaylor312 , but would you mind testing out the version of bindgen on my branch here: 

https://github.com/vados-cosmonic/wasmCloud/tree/fix(provider-wit-bindgen)%3Dmisimported-type

`fix(provider-wit-bindgen)=misimported-type`

I think the changes in there might fix the issue you ran into.

If you were to use it in your `Cargo.toml`, the import would look like this:

```toml
wasmcloud-provider-wit-bindgen = { git = "https://github.com/vados-cosmonic/wasmCloud.git", rev = "111c92266ebd0f105775f10d02f130dcec84b827" }
```

Or
 
```toml
wasmcloud-provider-wit-bindgen = { git = "https://github.com/vados-cosmonic/wasmCloud.git", branch = "fix(provider-wit-bindgen)=misimported-type" }
```
(I don't prefer the branch one, because it goes stale)

**Comment by vados-cosmonic** [comment]
Hi @wamli Do you have time to confirm that the fix I mentioned above works for you?

**Comment by vados-cosmonic** [comment]
got with @wamli and confirmed that this is fixed --  thanks for the contribution!
