### ISSUE TITLE
Support call aliases in a manifest file

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#199]
We would like to make it easier to write manifest files so that we aren't constantly filling the file with the cumbersome actor public keys. Instead, we would like to be able to use the string that is associated with the actor's `call alias` (which can be set and displayed using the `wash` command line).

Of course, the trick is in figuring out where to go get the actor from once you have its call alias. You won't know the call alias for the actor until you load the actor module itself.

Would love to hear additional commentary on this feature, alternatives, etc.

**Comment by stevelr** [comment]
- I like the idea of, at minimum, declaring an actor or provider as a yaml object with fields for file path/oci reference, and any aliases. so that you can refer to the alias in other places in the file.

- I found the makefile hack, using a wash command to inspect the claims and setting an environment variable before the `wasmcloud` command, to be cumbersome and not entirely reliable.

**Comment by stevelr** [comment]
- if manifest alias and call alias are different things, there needs to be a clear distinction. If we could make them the same thing, it would reduce confusion. I don't know if there is really a need to have two separate kinds of aliases.

**Comment by stevelr** [comment]
- certainly we need to be able to specify public keys in the manifest to be precise.
- however, during development, it would be great if we didn't have to specify keys at all. The first stage manifest interpreter could call the OCI registry or load the file to get the claims and determine the public keys. The response/data could be cached for faster response next time. that would need a --no-cache flag, or a separate clear-cache command if keys are changed.
