### ISSUE TITLE
[RFC] Replace Actix dispatch layer with OTP

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#203]
# Replace Actix Dispatch Layer with OTP

This RFC submits for comment the proposal that we switch from using Actix as our dispatch mechanism that handles communication between actors and capability providers and replace it with [OTP](https://erlang.org/doc/design_principles/users_guide.html).

## Summary

The activity being proposed would be replacing all of the high-level dispatch code currently written in Actix and Rust with Elixir/OTP. The new Elixir host runtime would replace the previous, and would re-use as much of the existing low-level code as possible through the use of native interaction with Rust crates (via [NIFs](https://erlang.org/doc/tutorial/nif.html)).

## Motivation

There are a number of motivations for this, each having varying degrees of urgency. The main motivation is that the current codebase, despite having been rewritten to be more easily consumed and contributed to, is difficult to understand and even more difficult to add new features. Decoding the spaghetti/web of actix interactions makes it so that, even though this runtime is better than the old one, it still remains entirely inscrutable to all but the original project creator and lead maintainer. In short, _no one is contributing to the core_ because no one _wants_ to contribute to the core because it's too much work and imposes too high of a cognitive burden.

Another motivation is related to hindsight. As we've been adding more and more dispatch and communication-related features, we've been asking ourselves, _"Are we building just another Kubernetes?"_. Thankfully, the answer continues to be "no". On the other hand, from a certain point of view we could easily say that what we're building looks an awful lot like OTP. The philosophy here is that if we're building "our own" OTP, then we should stop doing so and use the _real_ OTP to gain the benefit of its decades of increasing maturity, thriving ecosystem, and production deployment in some of the largest and most scalable environments in the industry.

## Design Detail

This design would include several important facets:

* NATS becomes mandatory. In order for us to support [polyglot providers](https://github.com/wasmCloud/capability-providers/issues/75) we need to be able to communicate with them using a reliable, free, and highly performant mechanism. NATS was chosen because of our existing investment in it for **lattice** support.
* The wasmcloud binary, which is basically a CLI designed to be stopped and started, gets replaced by an OTP application (or application suite) designed to run as a daemon/background process much like a database or other server. This process is always up, always available, and remotely controllable via CLI and **web application dashboard**.
* Existing integrations with the `wasmcloud-host` crate would be required to switch to using remote control over lattice. This includes the **krustlet provider**.

## Drawbacks

The most obvious drawback to this solution is the loss of the `wasmcloud-host` crate. This is the high-level functionality for embedders to insert a running wasmCloud host inside their own process. This would no longer be available and integrators would have to use lattice for remote control/interaction rather than crate embedding.

NATS becomes mandatory, which has the potential drawback of making the installation process a little more time-consuming. We think there are a number of ways to mitigate this, but it's still listed here as a drawback for completeness.

## Rationale and Alternatives

One of our biggest rationales is the _**deletion of code**_. By deciding that what we've done is build a pretty poor impersonation of OTP, we get to delete all of that code and rely on OTP, thereby following our own philosophy of _**eschewing boilerplate**_ in all its forms.

There are very few, if any, alternatives to this. We could continue with the existing code base, but evidence shows we will continue to have stagnant or non-existent contributions to the host core. We could rewrite the Rust code base to use a _different_ actor framework, but we feel we'd be back in the same problem as we are now, the rewrite just delaying more pain until the future. 

Adding new and powerful features today is untenable for all but the contributors who wrote the core in the first place. This is not a strategy for open source success or community building. We think the elegant, declarative syntax of Elixir and the _dramatic_ reduction in code will make the core more approachable and thus more likely to draw contributions and constructive feedback in the form of issues.

**Comment by brooksmtownsend** [comment]
Re: drawback 1, current users of the `wasmcloud-host` crate who are embedding the host into their application (perhaps with solely static capability providers) what is their upgrade path? With the re-use of some of our Rust crates, it feels like the interaction with the control interface will remain mostly the same, so the difficult part will be refactoring the `wasmcloud-host` commands into the lattice control commands, and then figuring out the proper way to launch the OTP host alongside their application. I think some upfront effort into making the elixir+NATS requirements as easy as possible to get in place, and an opinionated way to launch the host will help ease the pains there

**Comment by autodidaddict** [comment]
Yes for existing consumers that are embedding the `wasmcloud-host` crate, this will induce some friction. However, to my knowledge, there is only one team actually doing that, and that's Krustlet. We should be able to modify the Krustlet provider to work via lattice control interface and not embedded API calls.

One of the underlying assumptions that integrators can safely make is that wasmCloud will always be running. If it has been installed properly, then it's simply _there_ and available for use by making NATS calls.

We're also experimenting with a way to document both the lattice RPC API and the lattice control interface API in such a way that the definition is codegen-friendly. There's no reason you shouldn't be able to simply generate a lattice RPC or control client in your favorite language from our upcoming spec. @stevelr has been looking into all kinds of ways to describe APIs like this and we may be onto something with [Smithy](https://awslabs.github.io/smithy/), from Amazon.

**Comment by brooksmtownsend** [comment]
>One of the underlying assumptions that integrators can safely make is that wasmCloud will always be running. If it has been installed properly, then it's simply there and available for use by making NATS calls.

Big fan of this, the wasmCloud service should never be affected by actor/provider failures (which the old libloading process made us vulnerable to provider failures)

**Comment by jsoverson** [comment]
On the motivation: Actix documentation is a problem, but contributing to wasmcloud-host would still be difficult even if Actix was better. 

Wasmcloud-host only has ~12 tests. It's impossible to know if and when you break something. In the three largest files that house the bulk of distributed behavior and external contracts ([src/host.rs](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wasmcloud-host/src/host.rs), [src/messagebus/handlers.rs](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wasmcloud-host/src/messagebus/handlers.rs), [src/host_controller/hc_actor.rs](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wasmcloud-host/src/host_controller/hc_actor.rs)), there's only one test and it [doesn't test anything](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wasmcloud-host/src/host.rs#L783-L793). The main wasmcloud tests add some coverage but rely on external services and operate at a high level. If something does fail it's very difficult to know where and why it failed. I've tried to write tests but they require refactoring large portions of wasmcloud due to how interconnected everything is (e.g. testing something that requires a key in the lattice cache set by something else).

The gap for contributors can be bridged by improving test coverage and making wasmcloud-host best practices more clear. By best practices I mean things like should code be refactored to use [ErrorKind](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wasmcloud-host/src/errors.rs#L13) or should code that uses it be refactored to get rid of it? Is refactoring Result to use something like [anyhow](https://docs.rs/anyhow/) on the table?

On the proposal: The dispatch layer is not very complex at the core. A rewrite seems like a few steps beyond the current problems. Reinventing OTP in Rust is also not like reinventing Kubernetes. Kubernetes is a universal platform. OTP is a collection of software for a specific language. I love Erlang, but an OTP-like foundation in Rust sounds immensely valuable on its own.

**Comment by autodidaddict** [comment]
The wasmcloud host tests are in the integration suite, and there's way more than 1.

**Comment by autodidaddict** [comment]
>  I love Erlang, but an OTP-like foundation in Rust sounds immensely valuable on its own

The question is: are we writing a rust version of otpor are we writing a distributed web assembly host runtime? Our hedgehog isn't being an OTP library, its building wasmcloud.

**Comment by tadejstanic** [comment]
Reading this RFC and wanted to ask if you see any potential benefit of using this runtime https://github.com/lunatic-solutions/lunatic 

I'm not saying that it's possible to use it directly but maybe joining the forces/energy/time in order to bring a kind of distributed web assembly host runtime to the world. 

I think everyone how is interested in distributed systems via `wasm` is waiting for this kind of project to take off.

**Comment by autodidaddict** [comment]
I think our biggest concern is that what we've been building in Rust is basically just re-building the same concepts that OTP has been using for decades. If we were to somehow be able to work with or on top of  lunatic, we'd still have the same core problem - an incomplete Rust port of OTP.

**Comment by autodidaddict** [comment]
> I'm not saying that it's possible to use it directly but maybe joining the forces/energy/time in order to bring a kind of distributed web assembly host runtime to the world.

Bringing about a world in which applications are built on top of distributed WebAssembly host runtimes is absolutely my dream, and the more people who are involved in bringing about that reality, the happier I am.

**Comment by autodidaddict** [comment]
Link to the ongoing OTP experiment/work [here](https://github.com/wasmcloud/wasmcloud-otp).

**Comment by autodidaddict** [comment]
Link to Sasa Juric's talk on the soul of Erlang: [here](https://youtu.be/JvBT4XBdoUE)

**Comment by hardliner66** [comment]
I'm not sure if **replacing** the current dispatch system with Erlang/OTP is such a good idea. The current system makes it really easy to spin up a wasmcloud instance and use that to test things. Having another dependency would complicate that a bit. Also, there might be use cases where a native runtime would be beneficial over Erlang/OTP.

Maybe it's possible to modularize wasmcloud host in a way, so that we can keep the current rust version, while providing a way to swap out the runtime used for dispatch and build the Erlang/OTP version on top of that. This way people can still embed wasmcloud-host into their application, if thats a better fit for their use case. And people who want/need Erlang/OTP can use the Erlang wrapper.

This would also enable people to build their own custom runtime with a technology that better fits their needs.
For instance:
- [akka](https://akka.io)
- [orleans](https://dotnet.github.io/orleans)
- [bastion](https://github.com/bastion-rs/bastion)
- [CAF](https://www.actor-framework.org)
- [Pony](https://www.ponylang.io)

I think the simplicity (usage) of the current system is one of it's biggest strengths and combining that with the flexibility to use whatever runtime system you want would bring more benefits than just replacing it with Erlang/OTP.

**Comment by autodidaddict** [comment]
The current [experimental implementation](https://github.com/wasmcloud/wasmcloud-otp) is essentially a hybrid of Rust and Elixir/OTP, where it is re-using as many of the low-level Rust crates as possible. It doesn't, however, split in such a way that you could take the wasmCloud host runtime and embed it in something like Akka or Orleans (which would require it to still be Rust or another systems language for C FFI support).

**Comment by hardliner66** [comment]
I think it might be worth evaluating. I'm going to see if I can get a prototype running.

**Comment by brooksmtownsend** [comment]
@hardliner66 Thanks for adding your thoughts, the loss of the `wasmcloud-host` crate and the ability to embed it into other _Rust_ projects is one of the bigger drawbacks to the implementation in Elixir/OTP. It may incur an additional step to run (an Elixir distillery release vs a standalone binary) so the additional thought into the developer experience will be important.

**Comment by LiamRandall** [comment]
I would echo that in the new world ( per the RFC ) we would integrate as a daemon/background process.

**Comment by gembin** [comment]
Sorry for commenting on an old closed issue.  Per my understanding the main motivation was because of no contributor if using rust?  But currently impl is a mix of rust and Elixir/OTP, is it even harder for contribution?  The rust version isn't that complicated.

BTW, where can I find a working rust version of wasmcloud-host.   I tried `https://github.com/wasmCloud/wasmCloud/releases/tag/v0.18.2`, but don't know how to start the host if following the current doc,  it requires `--control-jwt` ,`--control-seed` etc. no doc mentioned how to get these.

**Comment by brooksmtownsend** [comment]
> Sorry for commenting on an old closed issue.  Per my understanding the main motivation was because of no contributor if using rust?  But currently impl is a mix of rust and Elixir/OTP, is it even harder for contribution?  The rust version isn't that complicated.
> 
> 
> 
> BTW, where can I find a working rust version of wasmcloud-host.   I tried `https://github.com/wasmCloud/wasmCloud/releases/tag/v0.18.2`, but don't know how to start the host if following the current doc,  it requires `--control-jwt` ,`--control-seed` etc. no doc mentioned how to get these. 
> 
> 

Hey @gembin, just to clear it up the primary motivation was due to our development efforts with actor frameworks in Rust. With our Rust-based version, we were essentially reimplementing features that Erlang/OTP had proven out for decades. Our goal with the rewrite was to leverage those alongside our Rust code bases. The hope for additional contributors, though it required Elixir knowledge, was due to the sheer amount of complexity the Rust code had that even puzzled Rust veterans.

That being said, it's really not recommended to start the Rust based version of the host if you aren't already using it and I'd recommend the elixir version with the current documentation

**Comment by gembin** [comment]
Thanks @brooksmtownsend, totally understand the motivation.  I've been working on rust for some years, but never touched  Erlang/OTP, that's why I asked for rust version.  So, except [wasmcloud-otp](https://github.com/wasmCloud/wasmcloud-otp), others components will remaining in rust, e.g. [capability-providers]( https://github.com/wasmCloud/capability-providers)?

**Comment by brooksmtownsend** [comment]
> Thanks @brooksmtownsend, totally understand the motivation. I've been working on rust for some years, but never touched Erlang/OTP, that's why I asked for rust version. So, except [wasmcloud-otp](https://github.com/wasmCloud/wasmcloud-otp), others components will remaining in rust, e.g. [capability-providers](https://github.com/wasmCloud/capability-providers)?

That's right, capability providers and actors will both retain Rust support as that is what developers will write when using wasmCloud, the only time you'll have to concern yourself with Elixir is if you contribute to the host runtime (which we'd love to have 😄 )
