### ISSUE TITLE
Prepare washboard for MVP

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmCloud#216]
Remove link to lattice view.
Remove unused or inaccurate metrics

**Comment by brooksmtownsend** [comment]
For this to be complete, I want to define some success criteria (going to repeat the above too):
- [ ] Remove the link to the lattice view, simply list the current host instead
- [ ] Remove the metrics widgets. They are useful to see running processes but don't currently show that much relevant information and we should have information in mind that we want to display instead of reaching for useful information
- [ ] Remove fancy "new" badges and other CoreUI placeholders (unsure if we have to keep anything with the template license?)
- [ ] Add error handling for start actor / start provider / define link. The user should at least be notified when an operation fails instead of the modal just disappearing
- [ ] Ensure modals do not disappear upon receiving a health check response

Those are some things that I can think of for now.
