### ISSUE TITLE
Support S3-Compatible Object Storage Services in Blobstore-S3 Capability Provider

### ISSUE THREAD

**Issue by ChihweiLHBird** [wasmCloud/wasmCloud#2287]
In the [README](https://github.com/wasmCloud/capability-providers/blob/main/blobstore-s3/README.md) of Blobstore-S3 Capability Provider, `AWS_ENDPOINT` is said to be only for testing purposes, and the docs didn't mention non-AWS S3 compatible object storage services, such as open-source storage systems like[Ceph](https://ceph.com/en/discover/technology/#object), or affordable Object Storage services like [Cloudflare R2](https://www.cloudflare.com/developer-platform/r2/).

I think it would be very nice to officially support all of these S3 compatible object storage services and make `AWS_ENDPOINT` be a production ready config option.

**Comment by vados-cosmonic** [comment]
Hey @ChihweiLHBird would you mind clarifying what you wanted here? 

Generally object storage services (with the exception of Azure) offer s3-compatible storage so that people can easily point tools made to work with AWS at their services instead -- so while the prefix `AWS_` isn't appropriate for accessing R2 for example, I'm not sure the name of the env variable is quite so important.

Are you OK with changing the variables from `AWS_` prefixed to `S3_` to avoid the mention of AWS in particular? That way we would more closely live up to the S3-compatible object store moniker?

**Comment by ChihweiLHBird** [comment]
Hi @vados-cosmonic, thanks for the response!

It was not about AWS mentioning or naming, but it's said that `AWS_ENDPOINT` is `For local testing purposes only, should not be used in production` in the environment vars section. In my understanding, `AWS_ENDPOINT` is usually used to set the non-AWS S3 service endpoint.

I just saw your PR to make clarify the environment variables way to configure the provider is only for AWS, which is nice, and I wonder if it is or will be possible to support non-AWS S3 configuration via env variables.

Thank you again!

**Comment by vados-cosmonic** [comment]
Hey @ChihweiLHBird thanks for the comment -- so the blobstore-s3 provider is focused on S3 as the compatibility layer between these stores, given that it's become the defacto protocol for blob storage.

That said, we absolutely can have different providers that support the individual features of the other non-AWS stores (and relevant different config) -- similar to how we have `sqldb-postgres` we can absolutely have `blobstore-azure` (in fact, [we *do*](https://github.com/wasmCloud/wasmCloud/tree/main/crates/provider-blobstore-azure)). 

I think right now we look at those other more specialized implementations as separate providers, rather than putting all the functionality into one. *Maybe* if the provider was just called `blobstore` it might work out, but we did call this one `blobstore-s3` for a reason! For anyone who wants to use Azure instead `blobstore-azure` might make more sense.

**Comment by ChihweiLHBird** [comment]
> Hey @ChihweiLHBird thanks for the comment -- so the blobstore-s3 provider is focused on S3 as the compatibility layer between these stores, given that it's become the defacto protocol for blob storage.
> 
> That said, we absolutely can have different providers that support the individual features of the other non-AWS stores (and relevant different config) -- similar to how we have `sqldb-postgres` we can absolutely have `blobstore-azure` (in fact, [we *do*](https://github.com/wasmCloud/wasmCloud/tree/main/crates/provider-blobstore-azure)). 
> 
> I think right now we look at those other more specialized implementations as separate providers, rather than putting all the functionality into one. *Maybe* if the provider was just called `blobstore` it might work out, but we did call this one `blobstore-s3` for a reason! For anyone who wants to use Azure instead `blobstore-azure` might make more sense.

Ah sorry about the confusion. By non-AWS store I specifically meant non-AWS but S3 compatible store, like Ceph.
