### ISSUE TITLE
[FEATURE] Built in HTTP server provider

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#2346]
Something that has long been discussed and requested amongst the community is the ability to have built in providers and autolinking for some of the most common providers. In order to keep this narrowly scoped, this issue lays out how to support providers and autolinking for a http server. However, the learnings here should inform how to build this for other common providers.

## What we need

To add a built in http provider, we're going to need to implement a few things. Most of these can be done separately from each other.

### Runtime support for http server

In the `runtime` crate, we need to add an http server (likely via `hyper` so it can be as performant as possible) implementation to the runtime implementations we provide to components. This will need to take configuration that identifies which port to listen on. Routing will be done via the Host header, which will map to the component ID that is given when starting a component. The host will not take care of any DNS routing or other information and the only requirement will be that the `Host` header is set. So if you were running a component with the ID of `foobar` on localhost with the wasmcloud host listening on port 8080, a curl request would look something like this:

```shell
curl -H 'Host: foobar:8080' http://localhost:8080
```

If possible, the builtin http server should still route to a component running on another host if that component isn't running locally.

The exact implementation details don't matter here too much, the main requirement is that the host only listens on a single port and then can do some basic routing to a component

### API handler changes (non-breaking)

The other large change will be support in the host for autolinking to a default provider. Starting and stopping a component should also now have a step to see if a default provider is running. Right now, this will just be for HTTP, but in the future, it would check for all configured autolinking interfaces. If the default provider is running, it will put a link for that provider into the lattice. This is because we still want the actual linking relationship defined and auditable via link. 

For the put_link endpoints, ff a user then puts another link between the component and a provider of the same interface, the autolink should be deleted (for now this is just the one interface, but we'll need more advanced logic in the future that can recreate an autolink for a subset of interfaces that might not have been "overridden" by a user-created link, but we'll cross that bridge when we need to). This means we will now need to store an additional boolean field (probably called something like `autolink`) with the link information in the data store. We can use this field to identify whether or not that was automatically linked. To start, this _should not_ be added to the public API, so we can evolve it if needed as we continue to grow our use of autolinking and default providers.

Please note that if a user wants to keep both a link to a default provider and a different provider (such as when having an ingress provider that routes traffic from the internet and using the default provider when on intranet or for debugging), they will need to explicitly link to the builtin as well as to the other provider. This applies to both imperative commands with `wash` or within a wadm manifest.

The name of the builtin should have a special prefix: `builtin:`. So for the http, this would be `builtin:http-server`. When we add more of these, they should follow a similar pattern

### New flags on the host binary

These features will require 2 new flags to be added to the host binary. Please consider these suggestions and feel free to modify in implementation:

- `--http <port>`: This flag will enable the built in http server to listen on the given port
- `--autolink`: To start, this flag will be a boolean that enables autolinking for the builtin http. In the future, we can extend this with additional configuration. See the last section in this issue for more information

PLEASE NOTE: Neither of these features will be on by default in the binary. See the next section for more information on how it will be used with things like `wash` and docker.

Later on we might add a flag like `--builtins` that let you enable multiple and deprecate the `--http` flag, but since http servers are core to so many services, I don't think it is a bad thing to have that flag around until at least 2.0

### Wash and helm chart updates

Obviously one of the biggest use cases for this new feature would be in developer workflows. As such, `wash up` should enable the builtin http by default with autolink enabled as well.

For our helm chart, the default should also be to enable builtin http. This should make the "kick the tires" mode easy when people install the wasmcloud-operator for the first time.

## Security implications

One important thing to note is that all invocations of the component that are done locally should still run through the policy service. This means we will need to generate a "synthetic" invocation that gets passed into the policy logic.

To avoid accidental exposure of a component when autolinking is enabled, the policy service can be used to deny or allow starting specific components if a host has autolinking turned on. Support for this information will need to be added to the policy service data structures. The other option for high security deploys is to _not_ enable any of the autolinking.

## Unknowns/open for discussion

Probably the biggest unknown here is whether or not we still need to show some sort of invocation on the `wrpc` topics for purposes of logging/tracking in the case where the http request is handled locally. As mentioned in the [security implications](#security-implications) section, we will still generate synthetic invocations that are passed to the policy service, but some users may prefer to have that invocation still be published on the wire for logging purposes. This could be done on a special topic like `wrpc.builtin.wasi:http.incoming-handler` (note: this is totally not a valid topic, just writing it out to illustrate the point). I'm curious if anyone has any feedback here.

## Things we can gloss over for now

As we continue to add more autolinking support for any arbitrary provider, we probably need a way to configure this that isn't just with flags/env vars as that would get really ugly to be mapping specific interfaces to providers and then what the autolink should look like. This means we'll probably need a way to express this within the config service and/or a separate host config file. However, the goal of this initial implementation will just be to get the logic working with a single builtin http provider

**Comment by rvolosatovs** [comment]
Thanks for writing this down, all sounds good to me!

Just have one question regarding the design here:

> If possible, the builtin http server should still route to a component running on another host if that component isn't running locally.

If I understand this correctly, you're suggesting that if, let's say there are 2 hosts running on two separate machines (virtual or otherwise, e.g. two containers), A and B.
- Both A and B have a builtin HTTP server running.
- A serves `foo:8080`
- B serves `bar:8080`

If A receives call for `bar:8080`, it proxies the request to B.

If the above is the correct understanding, then it seems like it would require, essentially, building a (very minimal) DNS service running on NATS, right? It appears that such system would imply some non-determinism, e.g. if we introduced a host C, which would also serve `bar:8080`, which host would the request received by A routed to? (I'm guessing that the non-determinism here is actually a desired feature, since that would allow for failover, 0-downtime upgrades and such)

**Comment by thomastaylor312** [comment]
@rvolosatovs My thinking was that since we're still requiring linking you could just publish it out just like the http provider does. So in your example, if A got a call for component `bar` (which is running on B or C), the host could then look up the link to that component and send it via the normal wRPC mechanism if it wasn't present on the machine.

One of the reasons I thought about when keeping the link is that in the future we might want to allow users to specify their own default providers/built ins, which could be normal providers. But even if we don't go down that route, using the link to route if it isn't found locally preserves the same behavior people expect currently. 

Did I misunderstand what you were saying or does that help clarify what I meant?

**Comment by rvolosatovs** [comment]
> @rvolosatovs My thinking was that since we're still requiring linking you could just publish it out just like the http provider does. So in your example, if A got a call for component `bar` (which is running on B or C), the host could then look up the link to that component and send it via the normal wRPC mechanism if it wasn't present on the machine.
> 
> One of the reasons I thought about when keeping the link is that in the future we might want to allow users to specify their own default providers/built ins, which could be normal providers. But even if we don't go down that route, using the link to route if it isn't found locally preserves the same behavior people expect currently. 
> 
> Did I misunderstand what you were saying or does that help clarify what I meant?

I saw the `Host` header being used for routing and assumed that would be domain name based, rather than component ID.

I'm concerned about (ab-?) using the `Host` header for specifying the component ID, in fact, I believe this would break most web applications, since it's generally expected that `Host` header is specified exactly once in all HTTP/1.1 requests.
A request sent to `example.com:8080` served by component `foobar` would have 2 with this design.
If we do want to use a header for this, I think we need to use a custom one. Potentially we could specify the original host in `X-Forwarded-Host` like a proxy would do, but I doubt that's what developers would expect. I don't think the component name should appear anywhere in the incoming HTTP request at all.
I generally don't think that the client should be able to select the component that would serve it's request, rather, it seems like the HTTP server plugin should either act as a proxy (using the domain name, not component ID), i.e. mapping `Host` header values to component IDs or only allow associating a single port with a single component.
What I'm saying is, that as an application developer, I should be able to write a component, which handles HTTP requests to `foo.example.com` and `bar.example.com`, served by wasmCloud listening on e.g. port 8080. I could use a reverse proxy, for example, to set up TLS for me and expose my service on actual domains and ports routing requests to `localhost:8080`. I would, ideally, not want to have to specify any extra config for this to work, in other words, I would not want to have to provision my component ID anywhere in my proxy config.
In cases without a proxy, I'm not sure how this would work in practice at all, since it appears that calling anything would require a custom header set at all times.

**Comment by ritesh089** [comment]
The lightweight nature of Wasm components in WasmCloud allows us to host a large number of components in a wasmHost . I dont think it should maintain the limitation of having to open a separate port for each component that serves requests over http.
There are some restrictions in some private cloud environments where you cannot open ports on demand for security reasons.
A single http server running on port 8080 should be able to handle http requests routed to any component.
In case of a reverse proxy implementation, there has to be some place in wasmCloud where the mapping of the route to componentId is maintained.
I think the thought process behind having to specify the component id in the header is to make this builtin lightweight because there would not be a need to maintain a mapping of routes to componentId's in that case.
The WADM anyways has the route information and component id details. Can wasmcloud just use this information to derive the component id based on the route instead of the client explicitly having to specify a certain host header with the component id?

**Comment by rvolosatovs** [comment]
If we do want to allow multiple components to share a port for MVP, I think the simplest and least surprising implementation would allow *domain names* to be specified as part of component/link metadata.
For example, a component `foo` could be configured to serve requests to `*.example.com` and `example.com`. A component `bar` could be configured with `myexample.com`. In result:
- `foo.example.com` would be routed to `foo`
- `test.example.com` would be routed to `foo`
- `example.com` would be routed to `foo`
- `myexample.com` would be routed to `bar`
- `foo.myexample.com` would not be routed
- `foo.bar.example.com` would not be routed

That's the lightweight DNS approach I mentioned.
What do you think?

**Comment by thomastaylor312** [comment]
So when linking to the builtin provider, would it expect to have config like `DOMAINS=*.example.com,example.com`? I think I'm ok with that!

**Comment by ritesh089** [comment]
> So when linking to the builtin provider, would it expect to have config like `DOMAINS=*.example.com,example.com`? I think I'm ok with that!

Actually the domain name doesnt need to change . 
In a real use case, the domain is 'something.example.com' . only the path will change .
eg :
'http://something.example.com/foo' will be routed to foo
'http://something.example.com/bar' will be routed to bar

**Comment by ritesh089** [comment]
Another important feature in this builtin should be to add the capability for the component to directly write to the outputStream od the incoming httpRequest.
When i check the invocationParams struct today , I only see the request body for http here :
https://github.com/wasmCloud/wasmCloud/blob/main/crates/host/src/wasmbus/mod.rs#L210
If we can pass the responseWriter down to the component, the component will be able to write the response directly . This will increase the throughput of the router component if any and also be more performant.
It will also make the wasmCloud host more flexible as components will directly be able to handle streaming without having to modify core components of the wasmCloud host.

**Comment by rvolosatovs** [comment]
> Another important feature in this builtin should be to add the capability for the component to directly write to the outputStream od the incoming httpRequest.
> When i check the invocationParams struct today , I only see the request body for http here :
> https://github.com/wasmCloud/wasmCloud/blob/main/crates/host/src/wasmbus/mod.rs#L210
> If we can pass the responseWriter down to the component, the component will be able to write the response directly . This will increase the throughput of the router component if any and also be more performant.
> It will also make the wasmCloud host more flexible as components will directly be able to handle streaming without having to modify core components of the wasmCloud host.

Components already use streaming for all HTTP functionality, the body type in that enum is actually the stream, that the component writes to.

**Comment by thomastaylor312** [comment]
> 'http://something.example.com/foo' will be routed to foo
> 'http://something.example.com/bar' will be routed to bar

This feels more like an L7 router where the component name is the top level of the path. I am not sure if that is going to be the best design or not for a built in
