### ISSUE TITLE
[FEATURE] Allow specifying a 'target' when deleting links

### ISSUE THREAD

**Issue by lxfontes** [wasmCloud/wasmCloud#2670]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

when deleting links we can't specify a "target" so if the source has multiple links it deletes the first one that matches the source / wit-namespace / wit-package.

Example:
two component ( hello-one and hello-two ) linking into 'http-server'

```
❯ wash get inventory


  Host ID                                                     Friendly name
  NAPHEQMLMLYDX7RBOANIS2BXCEXER3FZ24XGDQVIDXKFEZKYNBHP23CT    crimson-wave-1887

  Host labels
  hostcore.osfamily                                           unix
  hostcore.arch                                               aarch64
  hostcore.os                                                 macos

  Component ID                                                Name                       Max count
  hello-two                                                   http-hello-world           1
  hello-one                                                   http-hello-world           1

  Provider ID                                                 Name
  http-server                                                 HTTP Provider

# Adding first link
❯ wash link put http-server hello-one wasi http --interface incoming-handler

Published link (http-server) -> (hello-one) successfully

# Adding second link
❯ wash link put http-server hello-two wasi http --interface incoming-handler

Published link (http-server) -> (hello-two) successfully
❯ wash get links
 ⡀⠀


  Source ID     Target      WIT         Interfaces
  http-server   hello-one   wasi:http   incoming-handler
  http-server   hello-two   wasi:http   incoming-handler

# Here I'd like to delete the link towards 'hello-two' only, but can't specify a target
 ❯ wash link del http-server wasi http

Deleted link for http-server on wasi:http (default) successfully
# It seems to delete the oldest one
 ❯ wash get links
 ⡀⠀


  Source ID     Target      WIT         Interfaces
  http-server   hello-two   wasi:http   incoming-handler
```

### Describe the solution you'd like

Ability to pass a target when deleting a link. Something like
```
wash link del <source> <wit-namespace> <wit-package> --target <target>
```

Having `--interface` might also be interesting.

**Comment by brooksmtownsend** [comment]
I think this stemmed from an assumption that in order for one component (or provider) to link to another component, if the WIT namespace, package, and interface was the same, then you must use a `link_name` in order to differentiate the two links. In this case, the HTTP server uses an external indicator, the receiving HTTP address from the config, in order to determine which component to invoke.

For a workaround, today you can simply assign a link name for each of the additional links, and then you should be able to do:
```
wash link del foo wasi http --name mycomponent2
```

In the long term, we may want to reject these links, as it's not a valid use case for a component to link to two different targets with the same namespace, package, and interface.

**Comment by brooksmtownsend** [comment]
Oh, we nailed this down in #2963 !
