### ISSUE TITLE
[BUG] Config change errors in host log

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#2807]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

An error as shown below appears in the host log repeatedly

### Steps to reproduce

```
2024-08-20T12:19:17.096661Z ERROR wasmcloud_host::wasmbus::config: Config changed receiver errored, this means that the config sender has dropped and the whole bundle has failed error=channel closed
```

### Expected behavior

no errors

### Environment

- OS: MacOS
- Shell zsh
- wasmcloud `main`

**Comment by brooksmtownsend** [comment]
@vados-cosmonic What piece depends on the latest released version of the host here? Sorry I don't quite understand if `main` should show this error or not

**Comment by vados-cosmonic** [comment]
The error itself shouldn't show -- IIRC this was from the `changed().await` not having a way to pass an error through to the thing that was listening (so it wouldn't know when to disconnect/stop). IIRC this was caused by the listener that was delivering config updates to a spawned provider. Once an error like this occurred it was impossible to tell the difference between an error (and when to stop listening) and a truly empty config update IIRC.

This was [the commit where I changed the behavior](https://github.com/wasmCloud/wasmCloud/commit/1931aba6d2bf46967eb6f7b66fdffde96a10ae4d)
