### ISSUE TITLE
[BUG] `wash dev` does not work with TinyGo project

### ISSUE THREAD

**Issue by atifsyedali** [wasmCloud/wasmCloud#2887]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Modifying and saving a file while `wash dev` is running unexpectedly quits `wash dev` and the dev loop doesn't work. Reproducible with TinyGo. Haven't tested other languages.

### Steps to reproduce

1. Run `wash new component hello --template-name hello-world-tinygo` ... works
2. Run `wash dev` ... works.
3. Modify hello.go (e.g. change `Hello from Go!` to `Hello from Go!!!!`)...error in console

Logs:
```
 Starting project build
✅ successfully built project at [/tmp/whatever/hello/build/http_hello_world_s.wasm]
👀 watching for file changes (press Ctrl+c to stop)...

**the key should be 56 characters, but was 49 characters**
```

### Expected behavior

`wash dev` should work

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

**Comment by vados-cosmonic** [comment]
Hey @atifsyedali thanks for reporting this -- it looks like some code in `wash` was held over from when we still were using [NATS nkeys](https://github.com/nats-io/nkeys) as component IDs. 

This is a legitimate bug, so I've got a fix that will be merged soon, and we'll release a new patch version of `wash`.

**Comment by vados-cosmonic** [comment]
Hey @atifsyedali just an update here, it took a while, but please check out `wash-cli` version `0.32.0` (https://crates.io/crates/wash-cli) -- bug is fixed in that release!

You can also use the GH release:
https://github.com/wasmCloud/wasmCloud/releases/tag/wash-cli-v0.32.0

I've just tested it locally and you should be good to use `wash dev` and *also* change your golang files and see rebuilds :) :sweat_smile:
