### ISSUE TITLE
[FEATURE] Setup testing for exercising Provider SDKs against the `main` version of the host

### ISSUE THREAD

**Issue by joonas** [wasmCloud/wasmCloud#3188]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the solution you'd like

Due to a recent change I made in https://github.com/wasmCloud/wasmCloud/pull/3131 (addressed in https://github.com/wasmCloud/wasmCloud/pull/3186), the currently working (in this case `http-server` `v0.22.0`) Rust-based providers would fail to start as follows:

```shell
Error: failed to run provider

Caused by:
    0: failed to load host data
    1: Initialization error: parsing host data: unknown variant `http`, expected `Grpc` or `Http` at line 1 column 975:

...
```

Out of this, it occurs to me that we should have have tests that stand up providers written against the currently published version of the Provider SDK (both Rust and Go).

This way we could catch any backwards incompatible changes that might impact any of our provider-sdks (and thus providers written using that SDK) sooner.

**Comment by brooksmtownsend** [comment]
So on the reverse end what's the best way to ensure that the newest provider-sdks are working well with the currently released version of the wasmCloud host?

I like what we have for `wash` tests at the moment, where we test with `latest` and the last published minor version 😄 Since we have a 1.0 out there, I'd propose at least the last minor version
