### ISSUE TITLE
Actor live update optionally should enforce strict claims

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#35]
When live updating an actor, there is currently a check that `warn`s the user in the case that the new actor has more claims than the old actor. This prevents the case where an actor that is being hotswapped in is now signed for additional permissions than the original. Currently, we do not ensure that the claims list is the same, only that there aren't additional claims. This also leads to an edge case where you can change one of the capability claims of the actor, and we won't end up warning the user.

**[RFC] Strict claims check option**

I suggest that claims are compared by set intersect, and if the list of claims on the old and new actor differ then there should be the option to reject that live update. This can be in the form of a `bool` that is supplied to the HostBuilder, or something similar, that allows the developer to denote if they want to allow strict claims checking, similar to allowing latest OCI tags.

Implementing this as a toggle will still warrant a set intersect style of comparison, but instead with a warning denoting that the claims have changed so that the user will be aware of the change.

With strict claims checking, I think this will reduce the vulnerability that could _potentially_ be introduced by live updating actors that are distributed by a 3rd party.

**Comment by autodidaddict** [comment]
I love this idea. I think what we could do is make it so that if live updates are enabled, strict checking is the default (secure by default, defense-in-depth at all times). Then, you could optionally do `disable_strict_update_checking` or something similar which would loosen the restrictions to essentially where they are now. The wasmcloud host binary, once it has structopt in it, would be able to take these types of toggles as flags when executing.
