### ISSUE TITLE
Don't forget the Edge :)

### ISSUE THREAD

**Issue by aschrijver** [wasmCloud/wasmCloud#3545]
I was reading #3120 and have some feedback that's tangentially related.

Wasmcloud is part of Cloud-Native Computing Foundation and Cosmonic is a vendor in the cloud space. And it shows throughout the project, in docs and communication where cloud-related terminology is abundantly sprinkled about. Nothing wrong with that, and an active community is forming on Slack.

Yet as the diagram on https://cosmonic.com/product shows we're at "_Any Edge_, Any Cloud". And I feel that the whole part of Edge up to Cloud could get more attention within the project. That you are missing out on reaching a much larger audience.

Where wasmCloud is used in small-scale solutions, e.g. on the Small Web, decentralized social networks, local-first/p2p, or IoT. But the project is currently not very accessible or even attractive to people involved in such work, when they perceive it as mainly a 'big cloud' product. The risk is that the current audience and focus will indeed gradually make wasmCloud a bulky cloud product, that is overkill for these scenario's. Add multi-tenancy? Sure. Advanced clustering? Looks good.

The wasmCloud project might be structured so more clearly address stakeholder needs on the whole range from Edge to Cloud. For instance:

- If I am an IoT developer I'd like to know how to bootstrap the absolute "minimum core" wasmCloud profile.
- If I am a Local-first developer using Tauri I'd find instruction on how to integrate core + additional libs.
  - I'd find considerations whether or not to deploy NATS locally.
- If I am a Component developer I'd be delighted by the component-oriented development guide and SDK.
  - In the small-scale audience are plenty of Lego™ building block creators to help form a vibrant component ecosystem.

Well, that's the idea. A wasmCloud where all the steps from edge to cloud are like layers on an union. Optional if you only do Edge. But explicitly recognized to make the wasmCloud product as attractive as possible to the broadest audience. The one that is marketed in Cosmonic's diagram.

**Comment by brooksmtownsend** [comment]
Hey @aschrijver thank you for writing out your thoughts here, it's always great to hear your perspective 🙂 

I'm very happy to see people be successful on their own, in the edge, and in the cloud with wasmCloud. I think the general community shares this sentiment, but in my personal view, if it's running on a server somewhere, wasmCloud should the best application platform for running Wasm there.

I do want to mention that even though Cosmonic is a large contributor to wasmCloud, the difference in the marketing diagrams for the Cosmonic product and what's actually present in the wasmCloud project is a testament to our dedication to a community driven project. There will absolutely be differences to Cosmonic's goals and what is best for the wasmCloud community, and we'll continue to do what's best for wasmCloud over what's driving Cosmonic.

We've put quite a lot of effort into our cloud/k8s deployment guides lately because there's been lots of interest there. People running wasmCloud on k8s is an increasingly common scenario, and easy for us to focus on because k8s is fairly prescriptive. The edge is a little bit harder, with us considering experiments with everything from a raspberry Pi cluster to a Nerves installation to running on set-top boxes for Telcos. It's a wide ecosystem! We certainly have our eye on it though, keeping the wasmCloud host as minimal as possible and considering bundling in additional binaries to keep the deployment simple.

All that being said, we haven't forgotten about the Edge, we've just been responding to our latest feedback to help folks using the platform be successful in the cloud 🙂 Thank you for your suggestions for specific deployment and development guides, we'd love to consider those.

I'm going to close this issue for now since it's communicated its message well, but please feel free to offer additional feedback.

**Comment by aschrijver** [comment]
Thank you very much. Even the time and attention you spend on elaborate responses to inquiries like mine is truly amazing. Kudos to that dedication, and it is great way to foster vibrant community.

**Comment by brooksmtownsend** [comment]
Thank you @aschrijver 😃 Hope you have a wonderful week
