### ISSUE TITLE
Bring your own key storage

### ISSUE THREAD

**Issue by c00kiemon5ter** [wasmCloud/wasmCloud#360]
I watched the latest wasmCloud Community Meeting - 14 Jun 2023.

I really like the idea of being able to use Vault with wasmCloud.  
This would be a requirement for the things I work for.

I would certainly be interested in such a direction 👍

**Comment by brooksmtownsend** [comment]
So we can keep brainstorming here, I want to just draw out a few secret keys that wasmCloud uses throughout its lifecycle. There are:
1. [Nkey signing keys](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/nkey_auth): each actor and capability provider _must_ be signed with an issuer (account) and subject (module/service) key in order to run in wasmCloud. These, if not provided at build time, are stored under `~/.wash/keys` with a `600` chmod permission
2. Nkey cluster keys: Each wasmCloud host _must_ be launched with an nkey cluster seed, and an optional strict superset of corresponding cluster public keys. This key is used to sign each invocation that originates from this host, and the issuers are used to validate incoming invocations.
3. Nkey user keys, jwts, credentials: Each wasmCloud host _may_ use a combination of nkey user seed keys and an identity JWT, or a credentials file that combines both, in order to connect to NATS over its control interface, RPC, or provider RPC connection.

Did I miss anything here @autodidaddict? Really looking to outline where our keys are today so we can understand when `wash` would need to read from vault, when `wasmCloud` would need to read from vault, and what we could use to build something like this

**Comment by aschrijver** [comment]
I think this is a good enhancement that @c00kiemon5ter suggests. Was just discussing with someone about [Mozilla SOPS](https://github.com/mozilla/sops) vs. Hashicorp Vault. There's [some comparison](https://oteemo.com/hashicorp-vault-is-overhyped-and-mozilla-sops-with-kms-and-git-is-massively-underrated/) out there, but I am using neither atm. Hashicorp Vault is excellent, I've heard. But for me personally - and possibly to consider as a sensible default for wasmCloud too - I'd start with a support (tested integration) for SOPS. Why? Because this represents the keep-it-simple(r) approach (and Git storage is appealing to me), at the lower end of scalability requirements and the more vendor-neutral approach.

> I watched the latest wasmCloud Community Meeting - 14 Jun 2023.

For reference: [2023-06-14-community-meeting.md](https://github.com/wasmCloud/wasmcloud.com-dev/blob/main/community/2023-06-14-community-meeting.md)

This key storage is like an NFR and shouldn't that mean that something like a `wasmcloud:keystore` capability?

Aside: I really liked this terminology of ["encrypted data vault"](https://github.com/WebOfTrustInfo/rwot9-prague/blob/5de4411a93c25a329377d65af1d641bb6d51a811/final-documents/encrypted-data-vaults.md) (from Rebooting the Web of Trust conference 2019), more aligned with Solid project, the notion of "personal data vaults" that you give applications controlled access to.

**Comment by autodidaddict** [comment]
> This key storage is like an NFR and shouldn't that mean that there'd be something like a wasmcloud:keystore capability?

We do have an implementation of the `wasmcloud:keyvalue` contract supported by Vault, allowing the actor to think it's just reading/writing simple data while Vault is securing it under the hood. Is this what you're looking for or something more integrated?

[https://github.com/wasmCloud/capability-providers/tree/main/kv-vault](https://github.com/wasmCloud/capability-providers/tree/main/kv-vault)

**Comment by aschrijver** [comment]
Hashicorp received a ton of criticism with its move to BSL and many people vowing to move away from HC. I see that Vault is also under the [BSL license](https://github.com/hashicorp/vault/blob/main/LICENSE). An argument for BYOKS :)

**Comment by thomastaylor312** [comment]
@brooksmtownsend did we want to keep this around and mark so it doesn't go stale?

**Comment by aschrijver** [comment]
FYI a recent development around HashiCorp and their adoption of BUSL license is that after Terraform (to [OpenTofu](https://opentofu.org)) now the intent is to also [fork Vault into OpenBao](https://www.theregister.com/2023/12/08/hashicorp_openbao_fork/) under an MPL license and [as a Linux Foundation project](https://wiki.lfedge.org/display/OH/OpenBao+%28Hashicorp+Vault+Fork+effort%29+FAQ).

**Comment by aschrijver** [comment]
Is it stale?

**Comment by brooksmtownsend** [comment]
Now that you commented, it's not! The stalebot is a good reminder for us to come back to issues and figure out why we haven't had movement here. I know this is something we're interested in and I think the latest development is that we know we'll likely want to serve secrets to components using something like `wasi:runtime/config`, but behind the scenes wasmCloud should be assisting with pulling secrets out of a store 🤔

**Comment by thomastaylor312** [comment]
Bad stalebot, this wasn't stale
