### ISSUE TITLE
[RFC] Starting a newly created actor is too cumbersome

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#78]
In 0.15.0, the way a developer starts _their first ever_ actor is:

1. Create the actor with `cargo generate --git https://github.com/wasmCloud/new-actor-template`
2. Compile it with cargo, e.g. via `make`
2. Start (via `docker run`) a local OCI registry
3. Use `wash reg push` to shove the newly signed actor into the registry
4. Type `wash up` to launch a REPL
5. Type `start actor localhost:5000/whatever_i_pushed:mytag` 
6. Either use `call` to invoke the actor directly, or go through the cumbersome process of starting a provider and then using `link` to set configuration.

This is not the kind of frictionless experience that we want new developers to have. I think there are a couple of options here:

a. `wash` can be modified to `watch` a particular `.wasm` file and re-load it into the REPL's host every time the file changes, allowing for the cumbersome initial steps to be offset by a faster feedback loop that auto-triggers every time the `.wasm` is regenerated. This effectively allows a developer to bypass the OCI registry setup and push steps for initial experimentation.
b. create a cargo plugin `cargo run-actor` that takes the compiled `.wasm`, signs it with temporary claims, starts a wasmCloud host attached to the localhost lattice, and then fires up the actor.

Certainly open to other options, no matter how difficult they may seem. The point is that we (wasmCloud) should be absorbing complexity on behalf of our developers rather then foisting it upon them. The feedback loop for adding code to an actor and experimenting with it needs to be _extra fast_ and _brain-dead simple_ and I don't think we're quite there yet with 0.15.0.

**Comment by VestigeJ** [comment]
Some of these steps are assuming dev environment characteristics (maybe we can link back to another section of the docs for pre-reqs or assumptions). For example, https://github.com/cargo-generate/cargo-generate

**Comment by autodidaddict** [comment]
The docs that are either available now or in PR now talk about (and link to) cargo generate. My issue really isn't with the creation of a new actor from the template. My issue is the feedback loop:

1. See the actor in its current state
2. Add something to it to see how it changes the behavior
3. Observe the changed behavior, learning from it.
4. Goto 1

Transitioning from 2 to 3 is where we're currently (imho) introducing too much friction. This should be super easy and super simple, like hitting Ctrl-R in an IDE or hitting F5 on old-school ASP.NET websites that would launch a browser(tab) for you.

**Comment by ChrisRx** [comment]
Thoughts on:

1. Extending cargo with a custom command, something like `cargo-wc` so that it could be usable to generate the actor template with something like `cargo wc new [actor-name]`
2. Lazily start the local registry by adding that to the default target in the template `Makefile` OR maybe better yet start it as a part of wash with the aforementioned `watch` style command.  That is something I've been doing here that works for docker/podman:  https://github.com/criticalstack/crit/blob/main/internal/cinder/cluster/registry.go#L17-L37

**Comment by autodidaddict** [comment]
As for 1, we already have plans for `wash` to ultimately be the source for all of the scaffold generation for wasmCloud-supported languages. Getting from empty to scaffold is, even now, not all that painful. It's just the code-execute-improve cycle that is pretty high friction right now.

**Comment by autodidaddict** [comment]
Auto-spawning a local docker registry definitely sounds like it could take some friction out of the loop.

**Comment by LiamRandall** [comment]
1. agreed the lifecylce should be driven from wash
2. does the registry bring unnecessary complexity to the equation?
3. wash should be configurable to watch multiple active developments and reload upon modification; think 'hugo -D server' experience.  Autoreloading on each change - do we tie this to building or code change?
4. would a standard oci registry will support the kind of reload hook we want?

**Comment by autodidaddict** [comment]
2. The registry removes complexity from the first exposure scenario but adds it once you're ready to make your own actor. 

3. Agreed, though Hugo doesn't watch multiple sites. It should be triggered by compiled and signed artifact changing,  not code.

4. Registries don't support push hooks that I know of and monitoring it would add even more complexity

**Comment by brooksmtownsend** [comment]
Doing some thinking here, I don't think that we should have to use a local registry at all unless we want to mimic the functionality of a remote OCI registry. (e.g. I think it's good to have the option, but only for testing)

With the control interface, it's assumed that we're interacting with a host that is remote to where the control interface client is (e.g. with `wash ctl`, we aren't directly interacting with a local host unless we're in the REPL, or explicitly launch one). What if the control interface attempts to load an actor or provider from disk if the string is a valid path and not a valid OCI URI? We'll have a few hurdles here, one that I can think of is we may require absolute paths since we don't know what location the host / actor/provider will be.

If this is implemented, we skip launching a registry and pushing to that registry. If `wash` supports a no-nats REPL mode, then this also removes the need for docker / docker-compose at all

**Comment by autodidaddict** [comment]
>  What if the control interface attempts to load an actor or provider from disk if the string is a valid path and not a valid OCI URI? 

I like this. I'd also like to see how this can interact with the idea of manipulating the host directly rather than via NATS control interface, making it so that the `wash up` operation mode can work with zero pre-requisites, not even NATS or a local registry.

In other words, you should be able to `wash up` and `actor start` without NATS running and without a local OCI registry... but you should be able to opt-in to using NATS control and local OCI registry if you want.

**Comment by brooksmtownsend** [comment]
Agreed, https://github.com/wasmCloud/wash/issues/92 is filed for no-NATS mode with the REPL, I believe it would not be too high of an effort to get that mode working (actually wash worked like that originally 😃 ). I'm a big fan of removing the docker requirement to just get started

**Comment by brooksmtownsend** [comment]
Now that `wash` supports no-nats mode, and we can invoke commands on the host API directly, I'd love to add the ability to load a local actor file into a `wash` REPL host.
The logic flow would likely be (for a `ctl start {actor,provider}` command):
1. If the host is a remote host (not the embedded REPL host) send the command via the control interface (local resources not supported)
2. If the host is the local host, attempt to open the value provided as a file. If it exists, attempt to load the actor/provider from disk
3. If loading the file from disk fails, proceed as usual and assume that the reference is an OCI reference. If the OCI reference is invalid, then the control interface will fail to pull the file. 

The "default" behavior will likely be decided by how fast the control interface can fail if the value is not a valid OCI reference and how fast the `File::open` operation will fail if the value is not a valid file on disk. The operation that is the quickest should be attempted first.

In addition to this, I would still love to add in a command similar to https://github.com/jsoverson/wacl for quick iteration on actors only

**Comment by brooksmtownsend** [comment]
The flow would be trimmed down to:

1. Create the actor with `cargo generate --git https://github.com/wasmCloud/new-actor-template` or `wapc` cli-go
1. Compile it with cargo, e.g. via `make`
1. Type `wash up` to launch a REPL
1. Type `start actor ./target/wasm32-unknown-unknown/debug/myactor_s.wasm`
1. Either use call to invoke the actor directly, or go through the cumbersome process of starting a provider and then using link to set configuration.

**Comment by brooksmtownsend** [comment]
With https://github.com/wasmCloud/wash/pull/122, what do we think about closing this @autodidaddict ? I'd still like to implement the `watch` functionality for quick iterations, but starting the actor no longer requires the registry and is _much_ simpler

**Comment by autodidaddict** [comment]
As long as we've got a separate issue for the `watch` feature then I think we can close this.

**Comment by brooksmtownsend** [comment]
With the latest documentation at https://wasmcloud.dev/app-dev/create-actor/run/ showing off starting a local actor, and closing wasmCloud/wash#122, starting a local actor no longer requires the registry and is much lower friction.

https://github.com/wasmCloud/wash/issues/105 is the next step to improve the developer experience of quick iteration on actors, which is where we're going to improve the experience further. For now, the actor start experience is greatly improved, so this issue is done.
