### ISSUE TITLE
[BUG] `provider-wit-bindgen` usage requires an external dependency in `Cargo.toml`

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#801]
**Describe the bug**
Currently, code generated by `provider-wit-bindgen` may depend on `::serde_bytes` import, which may not exist in user's `Cargo.toml`

**To Reproduce**
1. Not sure, see https://github.com/wasmCloud/wasmCloud/pull/772#discussion_r1371763159

**Expected behavior**
No opaque third-party dependencies required in user's `Cargo.toml`

I would expect any third-party dependency to be re-exported

**Comment by thomastaylor312** [comment]
Yep, going back to the original linked thread that started this, I think it is probably better to reexport the needed dependency. I went back through most of the macros I used and this is the most common pattern. We had random opaque dependencies in wasmbus-rpc and those were a pain to deal with

**Comment by vados-cosmonic** [comment]
Hey @thomastaylor312 thanks for looking back through. 

This change though requires thinking about what to do with `serde`, and `wasmcloud_provider_sdk` as well. If we lock in a version (& features), that means people cannot use (or rename, unless we configure it), their deps or add features they want, in downstream code.

If we're fine with this risk, then I'm fine with making this change, but want it to be clear before we do, since it's not mentioned in the earlier discussion

**Comment by thomastaylor312** [comment]
You can still use two different versions of the dependencies, it just becomes a problem when using it with an exported type from the macro. Also, things like serde should be mostly compatible between minor versions

**Comment by vados-cosmonic** [comment]
Thanks for the crosscheck @thomastaylor312 , what do you think about `wasmcloud_provider_sdk`? That's the bigger concern IMO

**Comment by thomastaylor312** [comment]
I could go either way.  I feel like it is almost guaranteed that people will be using wasmcloud_provider_sdk directly when using this macro, so it feels like it might be better to avoid lockstep versioning by having that be the one thing we expect users to import. This could go away once we get to wasmcloud 1.0 and have 1.0 crate versions for things. @rvolosatovs curious on your thoughts here on whether you think that trade off would be worth it

**Comment by rvolosatovs** [comment]
> I could go either way.  I feel like it is almost guaranteed that people will be using wasmcloud_provider_sdk directly when using this macro, so it feels like it might be better to avoid lockstep versioning by having that be the one thing we expect users to import. This could go away once we get to wasmcloud 1.0 and have 1.0 crate versions for things. @rvolosatovs curious on your thoughts here on whether you think that trade off would be worth it

I have always thought that users would just have to import at most a single wasmcloud-specific crate to build a provider and what you outlined seems to suggest that that's the route we should take - i.e. `wasmcloud-provider-sdk` exporting a `generate!` macro or similar and the macro itself relying on re-exports from the SDK crate.
That's, again, a very common pattern in the ecosystem and is also something we do in `wasmcloud_actor` already

**Comment by t3hmrman** [comment]
Tying `wasmcloud-provider-sdk` is also fine, but means we must release in lockstep when large changes are made to the provider SDK (which is reasonable anyway, since most improvements to bindgen we'd want carried over to when people *generate* providers).

This will have the effect of making backwards compatibility harder to reason about/achieve, because currently the host has no meaningful E2E tests and breaks other things frequently. If the host changes and forces a change in the provider SDK, this means an instant breaking change for bindgen. To be fair, this is basically what happens now -- the host changes and stuff breaks.

Bindgen was originally written to be a single import -- it was changed after some discussion, so @thomastaylor312 if you're OK with this change, I'm good with it :+1:

**Comment by vados-cosmonic** [comment]
Tying `wasmcloud-provider-sdk` is also fine, but means we must release in lockstep when large changes are made to the provider SDK (which is reasonable anyway, since most improvements to bindgen we'd want carried over to when people *generate* providers).

This will have the effect of making backwards compatibility harder to reason about/achieve, because currently the host has no meaningful E2E tests and breaks other things frequently. If the host changes and forces a change in the provider SDK, this means an instant breaking change for bindgen. To be fair, this is basically what happens now -- the host changes and stuff breaks.

Bindgen was originally written to be a single import -- it was changed after some discussion, so @thomastaylor312 if you're OK with this change, I'm good with it :+1:

**Comment by thomastaylor312** [comment]
Yep I am ok with the change, go ahead and we can iterate from there as we run into any problems!

**Comment by vados-cosmonic** [comment]
This was just merged:

https://github.com/wasmCloud/wasmCloud/pull/1344
