### ISSUE TITLE
[FEATURE] `wash drain linkdefs`

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#851]
**Is your feature request related to a problem? Please describe.**
`wash drain` is designed, not just as a pun, primarily for cleaning up resources that may be left behind after running wasmCloud. Today, this includes caches for OCI downloads, downloaded files for `wash up`, and smithy file cache. We still leave behind claims and link definition information in NATS KV, which will persist in the Jetstream data directory.

**Describe the solution you'd like**
 I would love to extend `wash drain` to also have the ability to remove claims and link definitions from a specified lattice. This should be done by connecting and authenticating to a NATS server and running the equivalent of `nats stream purge KV_LATTICEDATA_<lattice>` using **async_nats** in order to remove all entries from the KV stream.

**Describe alternatives you've considered**
We could simply remove the jetstream data directory, but this requires knowledge of where that directory is and would prevent us from using this functionality for a remote running NATS server.

**Additional context**
Related issue: https://github.com/wasmCloud/wasmCloud/pull/532. Thanks @Iceber !

**Comment by connorsmith256** [comment]
I did some thinking about this. If wash directly accesses the lattice metadata bucket, we'll have to implement specific key scanning logic to distinguish between claims and links. And direct bucket access was removed from the control interface in v0.31.0 for good reason, so I'd like to not re-introduce that pattern.

What if instead, we added a `.claims.del` subscription to the control interface, and let hosts clean up claims on behalf of clients? That keeps access to the bucket consistent (proxied through hosts).  However, this does mean in order to `drain claims/links`, a host needs to be running

@brooksmtownsend thoughts?

**Comment by connorsmith256** [comment]
@brooksmtownsend bump :)

**Comment by brooksmtownsend** [comment]
I like that approach to have a host handle access, since we really only add claims while hosts are running anyways. 

I wouldn't mind an additional kv delete for the lattice data bucket in wash, but just a complete wipe rather than individual deletes. This requires a NATS connection anyways and is more of a brute force way of clearing everything

**Comment by vados-cosmonic** [comment]
Hey @brooksmtownsend is there any overlap here with the recent `--purge` work? I know it's not quite on `wash drain`, but the purging of Jetstream state is happening now

**Comment by brooksmtownsend** [comment]
Oh, yes! I think the purge work takes care of this 😄
