### ISSUE TITLE
Implement span-based call tracing throughout host

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#9]
This was originally thought to be an OpenTracing thing but it's possible that OpenTelemetry might be the better approach? The main requirement is that we need to be able to trace the first stimulus through all calls resulting from it and then be able to emit that entire span, along with suitable metadata. For reference, see [this issue](https://github.com/wascc/wascc-host/issues/5) from the archived repository.

**Comment by Spora-GH** [comment]
been working on it, will upload current status by end of weekend...

was closes to doing that a couple of weeks ago but i had to chop it up once I'd seen the new arch, there are a few immediate benefits but also a couple of challenges, will send you a link by Monday morning

**Comment by Spora-GH** [comment]
it's an opentelemetry package for tracing and metrics... absorbing the prometheus middleware from the original host.

once I'd thought through the fact that wascc host is now able to switch out messaging providers and I'd made the adjustments, a few interesting ideas came to mind... will outline in an issue.

Apologies for not communicating, I managed to get malaria again, 4 months after the first (never expected that to happen) and 2020 keeps upping the crazy so I haven't had as much keyboard time as I'd expected to this year... since it was the oldest issue and still at the bottom of the pile, I thought it was still an undesirable :)
