### ISSUE TITLE
[BUG] Deploying a new wadm.yaml with a new revision but the same file:/// path for spec.components.properties.image does not reload the image

### ISSUE THREAD

**Issue by markenzie** [wasmCloud/wasmCloud#926]
I am following the Getting Started guide on the website. 

When I update the revision in my wadm.yaml file but not the image and deploy, it does not update the app. 

I am using a local file:/// path and building the image with `wash build`. 

The app only gets updated if I `wash down` and then update the revision again then redeploy.

It will also update if I change the path to the image under spec.components.properties.image to a new location. 

Merely deleting or messing with the file on the filesystem does not do anything. 

For example, I would build, rename file:///app/hello_s.wasm to file:///app/hello_s2.wasm manually, update the image (and revision) in wadm.yaml. Then a `wash app deploy wadm.yaml` would work. Then the next build-deploy loop would involve me renaming (and updating the wadm.yaml) to hello_s3.wasm, hello_s4.wasm, etc. 

**To Reproduce**

1. Build hello template and use local file:/// path to image
2. Deploy
3. Make change to source file
4. Rebuild
5. Deploy

**Expected behavior**
New image is deployed.

**Environment (please complete the following information) **
 - OS: Ubuntu
 - Shell: bash
 - wasmcloud Version: 0.21.1

Thanks.

**Comment by connorsmith256** [comment]
Hi @markenzie, thanks for the issue! I believe this is happening because [wadm](https://github.com/wasmcloud/wadm) only uses the component reference (in this case, a `file://` reference) to compare the contents of the manifest to what's running in the lattice. If the bytes change on disk, but the file path is the same, it looks like the app is correctly deployed. But as you point out, it would be nice to be able to handle this inner-dev-loop scenario and have the host re-load the component.

@brooksmtownsend @thomastaylor312 I'm thinking out loud here, but could/should the properties for an actor component in a manifest include an optional revision, to help disambiguate (since the revision is present in the host's inventory)? Though I just noticed revision is not in the `actor_started` or `actors_started` events :/ Or perhaps wadm's scalers should treat `file://` references as a special case, where instead of issuing `scale` commands, they issue `update` commands? Do you have other ideas for how we could support this?

**Comment by markenzie** [comment]
Hi @connorsmith256 thank you for getting back to me so prompty.

Before bed last night I got to thinking that this is actually working as intended as you say - images on a registry work the same way too. The :latest tag on an image is treated differently by tools though - usually requiring hitting the image manifest and manually finding the latest version. Could something similar be supported for file:// paths? Like `file:///app/hello_s.wasm:latest` - this might be an issue too though since that is a valid filename on Linux (but it could be just defined "if its a file:// path, attempt to strip :latest off the end first, always".

Maybe using the hash of the filecontents as the component reference instead of the literal path? Or a combination of filepath and last modified time?

**Comment by markenzie** [comment]
I think that makes sense and would work for my use case. I like that a user has to initiate the update manually so it is more clear what is going on.

The only thing I would still be confused about:

Say v0.0.1 is using a certain file:// and then v0.0.2 uses the same file, which (assuming the above change) results in an `update` of the file refernece when deployed. If I then undeploy v0.0.2 and go back to v0.0.1 - which file:// version is it going to load? The version of the file that existed when v0.0.1 was originally deployed, or the new version that was deployed with v0.0.2?

Thanks!

**Comment by connorsmith256** [comment]
Based off the way the host works today, if you were to "downgrade" to v0.0.1 of the manifest, wadm would instruct the host to start the component at the file reference contained in v0.0.1. The host would read whatever bytes happen to be on disk at that file path (the host doesn't cache file-based artifacts). Hope that helps!

**Comment by connorsmith256** [comment]
I filed an issue in the wadm repo to track this proposed work, so I'm going to close this issue
